### ISSUE TITLE
What is this magic number?

### ISSUE THREAD

**Issue by DannyBen** [jjmontesl/codenamize#3]
May I ask what is the meaning and purpose of the big number in this line?

```python
obj_hash = int(hh.hexdigest(), 16) * 36413321723440003717
```

**Comment by jjmontesl** [comment]
In previous versions, codenamize suported hashing integers without converting them to strings.

But because of the "consecutive numbers yield differentiable codenames" requirement, integers could not be used without distributing them over output space. This number is a large prime, which evenly distributes an input number over an output space of any size in a non-consecutive way.

I guess that, now that numbers are converted to strings and hashed, this may not be needed, but removing it would break name mapping compatibility with previous versions. It should probably have been removed along with the change that changed the hashing functions.

A comment must be added to remind removal (and test) in the next version that introduces breaking changes.

**Comment by DannyBen** [comment]
Thanks.

I ported this lovely piece of code to ruby (presenting: [concode][1]), and this was the only bit that was not documented. I left it in, so my ruby version is generating the exact same output as codenamize.

[1]: https://github.com/dannyben/concode

**Comment by jjmontesl** [comment]
This is awesome! Thank you!

I added information about concode to codenamize doc.

**Comment by DannyBen** [comment]
Sweet!
