### ISSUE TITLE
A similar project written in C#

### ISSUE THREAD

**Issue by Heaven31415** [jjmontesl/codenamize#6]
Hey, I really like your project and I wanted to ask if you know a similarly working library to codenamize that is written in C#?

**Comment by jjmontesl** [comment]
Hello!

I'm afraid I don't work much in C# nowadays, so I don't know if there's any library for this.

If you happen to port it, I'd be glad to link your project. Other people has ported the project to Javascript and Ruby. If you do so, I suggest you try to maintain compatibility with the generated output by codenamize, since all the related projects generate the same output for the same input.
